CC=g++
CFLAGS=-Wall

all: g0 g1 g2 g3 g4 g5 g6 g10

g0:
	$(CC) $(CFLAGS) generator0.cc -o g0

g1:
	$(CC) $(CFLAGS) generator1.cc -o g1

g2:
	$(CC) $(CFLAGS) generator2.cc -o g2
	
g3:
	$(CC) $(CFLAGS) generator3.cc -o g3
	
g4:
	$(CC) $(CFLAGS) generator4.cc -o g4

g5:
	$(CC) $(CFLAGS) generator5.cc -o g5
	
g6:
	$(CC) $(CFLAGS) generator6.cc -o g6
	
g10:
	$(CC) $(CFLAGS) generator10.cc -o g10
	
clean:
	rm -f g0 g1 g2 g3 g4 g5 g6 g10 mys0*