CC=g++
CFLAGS=-Wall

q1:
	$(CC) $(CFLAGS) q1.cc -o q1

q2:
	$(CC) $(CFLAGS) q2.cc -o q2

q3:
	$(CC) $(CFLAGS) q3.cc -o q3

q4:
	$(CC) $(CFLAGS) q4.cc -o q4
	
q5:
	$(CC) $(CFLAGS) q5.cc -o q5

clean:
	rm -f q1 q2 q3 q4 q5 outfile.txt

